# DISA STIG:
#   SRG-NET-000230-RTR-000003
#   Severity: medium
#   Rule ID: SV-221073r999682_rule
#   Identifiers: SV-110965, V-101861, CCI-000366, CCI-002205
#   Title: The Cisco switch must be configured to use keys with a duration not exceeding 180 days for authenticating routing protocol messages.
    [SV-221073r999682_rule] Configure routing protocol key chain with <180-day lifetimes
  cisco.nxos.nxos_config:
    lines:
      - key 1
      - key-string 071739545611011d0f0a13141c
      - send-lifetime 00:00:00 Jun 30 2025 23:59:59 Dec 27 2025
      - accept-lifetime 00:00:00 Jun 30 2025 01:05:00 Dec 28 2025
      - key 2
      - key-string 070C285F4D06
      - send-lifetime 00:00:00 Dec 28 2025 23:59:59 Jun 25 2026
      - accept-lifetime 23:55:00 Dec 27 2025 01:05:00 Jun 26 2026
    parents:
      - key chain OSPF_KEY
    match: line
    replace: line
    save_when: changed
